version: '3.1'
services:
  backend:
    container_name: test-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: test-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - '22181:2181'

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: test-kafka
    ports:
      - '39092:39092'
      - '29092:29092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_BACKEND://backend:29092,PLAINTEXT_LOCAL://localhost:39092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_BACKEND:PLAINTEXT,PLAINTEXT_LOCAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
